### PR TITLE
Minor changes here and there.

### PR DESCRIPTION
**Pull request by MastaCoder**
This causes the cells  to slow down and lag on the server. So removing it is the best option at the moment.

I had to do this all on GitHub online because I don't have Desktop on my new computer yet :+1:

### CODE REVIEW

**Comment by MastaCoder** [comment]
And chat now works too.

**Comment by MastaCoder** [comment]
Some configuration options from Cigar added too. Fixed some formatting in gameserver.ini and the default values.

**Comment by Logan7432** [comment]
Whats the diffrents from The orginal cigar and @itzlevie cigar?

**Comment by MastaCoder** [comment]
@Logan7432 It has some of the features from Ogar, however still not fully stable.

**Pull request merged**
